### ISSUE TITLE
Introspection endpoint fails with JWT profile

### ISSUE THREAD

**Issue by rebsp** [smartive/zitadel-net#369]
Installed nuget package version: 5.0.14

Following the documentation from here: [Authentication in Web APIs](https://github.com/smartive/zitadel-net/tree/main/src/Zitadel#authentication-in-web-apis) the Basic Auth with `client_id` and `client_secret` successfully validates the access token whereas the JWT profile does not. I'm able to load and parse the JSON from string and from file but the endpoint returns `Unauthorized` with the same test user in contrast to when using Basic Auth. 

Are you able to reproduce this on your end? 
Thanks & best regards

**Comment by buehler** [comment]
Hey @rebsp 

Can you try to successfully parse the application from the JSON? RSA keys are picky sometimes when used in JSON.

In another project, we use it like follows:
```csharp
public sealed class OidcConfig
{
    public string Issuer { get; init; } = string.Empty;

    public string JwtProfile { get; init; } = string.Empty;
}

.AddZitadeltrospection(
                "zitadel-v2",
                options =>
                {
                    options.Authority = _appConfig.Oidc.Issuer;
                    options.JwtProfile = Application.LoadFromJsonString(_appConfig.Oidc.JwtProfile);
                });

```

When you're able to successfully parse the application, the lib should allow you to authorize correctly. We do not experience the same issues. (This is an application that runs in production with 3000 users)

**Comment by rebsp** [comment]
Hey @buehler thanks for the fast response!
> Can you try to successfully parse the application from the JSON? 

It parses successfully, but yeah I'll try again with your approach. I assume you are mapping a config section to that `OidcConfig`, right?

**Comment by buehler** [comment]
Exactly.
The JSON is correctly escaped, and the application is correctly parsed.

Do you use ZITADEL v1 or v2 (the cloud one)?
Do you have a ZITADEL instance and the correct issuer url and other configs?

**Comment by rebsp** [comment]
v2.17.1 via Docker but you are right the issuer could actually be the culprit, I'll let you know asap

**Comment by buehler** [comment]
In my case, most of the time I forget the trailing slash in the issuer url.
