### ISSUE TITLE
Problem with Zitadel.Credentials.ServiceAccount.AuthenticateAsync and iat being in the future

### ISSUE THREAD

**Issue by nmutsch718** [smartive/zitadel-net#474]
I am having 2 problems. The first one is an issue that I can't seem to resolve using the Zitadel SDK following this code example to Authenticate a service account: https://github.com/smartive/zitadel-net/blob/main/examples/Zitadel.ApiAccess/Program.cs

I am getting back a response from my zitadel cloud instance of `issuedAt of token is in the future: (iat: 2023-04-10 22:18:07 +0000 UTC, now with offset: 2023-04-10 22:18:06 +0000 UTC)\"` I don't know why the server is telling me my issuedAt time is in the future. I don't even know how to specify the criteria the determines the issuedAt but I believe this is potentially a Daylight Saving Time bug. I'm not 100% sure. I'm getting the exact same issue when running Zitadel's tests locally as well. My machine is in Central Daylight Time GMT-5 (When Standard it's -6 GMT), but we are currently in a daylight saving time period. Again, this is just a theory, but I'm wondering if somehow it's a timezone or daylight saving time related issue.

![image](https://user-images.githubusercontent.com/8094893/231303160-3ce238f4-0db6-4ca1-8fbd-ac33a46c38a8.png)
![image](https://user-images.githubusercontent.com/8094893/231303192-fbc0d3bd-3dab-4475-9fc1-0db401c0983e.png)
![image](https://user-images.githubusercontent.com/8094893/231303709-bdcb6a9d-fad7-49ce-8f34-0e22543b87be.png)

The second concern I have, is that I wasn't able to even find this error message without downloading the Zitadel c# sdk source code and importing it locally to my project as a project reference, because the zitadel gRPC calls were just returning a very generic response like this:  `Error starting gRPC call. HttpRequestException: Response status code does not indicate success: 400 (Bad Request).", DebugException="System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).")` I had to dig all the way into `Zitadel.Credentials.ServiceAccount.AuthenticateAsync` to find a meaningful error message to work with. EnsureSuccessStatusCode() was converting the message that the Zitadel api was actually returning into "400: Bad Request". I think the fix would be to append original error message from the cloud api as opposed to completely replacing it

**Comment by buehler** [comment]
Hey @nmutsch718 
The thing with the error messages is an issue - I agree. I need to think about that.

Just had the same issue with the future problem. There are two solutions (the error is correct, the issuedAt field is in the future):

- You need to re-sync your local systems time with any time server to be on the same second as the server.
- You can configure "time skew" in ZITADEL to have a +/- range in seconds.

As I wrote, I just had the same issue locally and after a time sync, the tests worked again.
