### ISSUE TITLE
message.State is null or empty.

### ISSUE THREAD

**Issue by vitalybrandes** [smartive/zitadel-net#871]
I am getting AuthenticationFailureException: OpenIdConnectAuthenticationHandler: message.State is null or empty. if iam tring to use Zitadel for Razor pages in .net 8

**Comment by buehler** [comment]
Is this still an issue? Right now, I never used it with .net8.0 but it should basically work the same.

**Comment by vitalybrandes** [comment]
I never goes back to this issue again.
