### ISSUE TITLE
Omitt out of support dependencies

### ISSUE THREAD

**Issue by DerGary** [smartive/zitadel-net#923]
The Dependency `Microsoft.AspNetCore.Authentication` is out of support and contains known security vulnerabilities: 

![image](https://github.com/smartive/zitadel-net/assets/4302467/79c024e7-2803-46f8-b1e7-653e38a48252)
![image](https://github.com/smartive/zitadel-net/assets/4302467/e1d559dd-8481-4498-b931-58af0905b793)

![image](https://github.com/smartive/zitadel-net/assets/4302467/eb6eaa21-5b5a-4211-ae86-95b093199b46)

Please change the library to not depend on it.

**Comment by assi010** [comment]
I saw the PR did not pass the checks, but since there are no logs available anymore and no further comments I am unsure as to what was the issue. Is there any reason this is marked as completed yet the PR is closed?

**Comment by buehler** [comment]
Hi @assi010 

Yes, the deprecated packages were updated in another PR.

**Comment by assi010** [comment]
Thanks for the quick reply @buehler! I seem to have misunderstood then, I thought this was about this specific depencendy: `Microsoft.AspNetCore.Authentication` version `2.2.0` which still seems to be referenced.

Should I make a separate issue for that one?

**Comment by buehler** [comment]
Hey @assi010 

Oh, this was not removed yes.
I think it is beneficial if you'd create a second issue for this!

Thank you!
