### ISSUE TITLE
Login using the same browser after being idle / token expired results in an exception

### ISSUE THREAD

**Issue by sbosor** [smartive/zitadel-net#927]
Hello!

I am using .Net 8 and I have used this package to integrate with a self hosted instance of Zitadel.

What I have noticed was that after being logged in, when the IDToken expires, I am always receiving an exception when trying to login again. This was never encountered on Firefox. Also, I am able to access my Zitadel instance. 

Steps:
1. Login with a user in either Chrome or Edge.
2. Wait for the ID token to expire (12 hours in my case).
3. Open a new tab and try to login in.

Result:
An exception is encountered.

The errors logged on the .NET side, in Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler is:
1. `Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_request', error_description: 'Errors.AuthRequest.NotFound', error_uri: 'error_uri is null'.
`
2. `Message contains error: 'invalid_request', error_description: 'Errors.AuthRequest.NotFound', error_uri: 'error_uri is null', status code '404'.
`

Configuration: I have the same configuration as the one presneted here and I am using the latest version of the Zitadel package (v.6.1.2):
https://github.com/smartive/zitadel-net/blob/main/examples/Zitadel.AspNet.AuthN/Program.cs
```
.AddZitadel(
            o.Authority = "...";
            o.ClientId =  "...";
            o.RequireHttpsMetadata = true;
            o.SignInScheme = IdentityConstants.ExternalScheme;
            o.SaveTokens = true;
)
.Configure(
        o =>
        {
            o.Cookie.HttpOnly = true;
            o.Cookie.IsEssential = true;
            o.Cookie.SameSite = SameSiteMode.None;
            o.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        });
```

Another problem with this issue is that I also couldn't replicate it on my dev environment in order to try debugging it better.

**Comment by sevensolutions** [comment]
@sbosor i found your issue here and i dont know if its related but iam experiencing something similar.

https://github.com/zitadel/zitadel/discussions/7961

**Comment by buehler** [comment]
Well, the examples have not been updated in a while ;-)
I do not know if they work as expected currently.

**Comment by buehler** [comment]
This should work now right?

**Comment by sbosor** [comment]
> This should work now right?

It now works only due to a workaround that is explained here: https://github.com/zitadel/zitadel/discussions/7961
