### ISSUE TITLE
Microsoft.AspNetCore.Authentication is deprecated

### ISSUE THREAD

**Issue by assi010** [smartive/zitadel-net#942]
The package [Microsoft.AspNetCore.Authentication](https://www.nuget.org/packages/microsoft.aspnetcore.authentication/) version `2.2.0` has been released in 2018 and has deprecated for a long time. Referencing this nuget package results in multiple vulnerabilities being included through its dependencies such as https://github.com/advisories/GHSA-ghhp-997w-qr28.

In the Microsoft docs [#1](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-9.0&tabs=visual-studio) and [#2](https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-9.0&tabs=visual-studio#remove-obsolete-package-references) , it is explained that AspNetCore packages are no longer published on nuget since dotnet `2.2` and should be replaced with a FrameworkReference when used in class libraries. However, in my own testing locally it seems like removing the nuget reference altogether does not break the build or the tests. 

Please consider either removing the reference or changing the current reference from a PackageReference to a FrameworkReference. 

Thanks!

**Comment by buehler** [comment]
Thank you for the new issue!

I would much appreciate a PR/MR for this!
Currently, I'm on a very tight schedule and do not have a lot of time left to work on such projects.

**Comment by assi010** [comment]
No problem! I have created the PR, just let me know if there is anything else I can do.
